# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20170915_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='Description',
            field=models.CharField(default='', max_length=20),
        ),
    ]
